### ISSUE TITLE
Axios Error

### ISSUE THREAD

**Issue by joeljerushan** [val-bubbleflat/laravel-vue-validator#1]
could you please tell me how to handle error with axios ? that would be great if this added to readme.

**Comment by val-bubbleflat** [comment]
For now, this package handle only error for vue-resource. 
You can fork this project and add an axios interceptor to index.js (alongside vue-resource one) to handle them. If you do that, feel free to add a PR :)

**Comment by Chalkin** [comment]
I just improved it locally. I will add a PR soon.
